name: Release

on: push
  
jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest

    #if: github.event.pull_request.merged

    steps:
      - name: Compute next SemVer tag
        id: semver
        uses: happydemics/semver-release-action@master
        with:
          release_branch: master
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.base_ref }}

      - run: make update_action
        env:
          VERSION: ${{ steps.semver.outputs.tag }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release ${{ steps.semver.outputs.tag }}
          branch: master

      - name: Create release
        id: tag
        uses: happydemics/semver-release-action@master
        with:
          release_branch: master
          tag: ${{ steps.semver.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
